Rename supplier to retailer + documentation
tum-ewk/lemlab pull request #7
Opened 2021-06-14 09:19 UTC by sdlumpp

Documentation Chapter 1
Renamed supplier to retailer

2021-06-14 13:20 UTC, TUM-Doepfert requested changes
Please see comments.

2021-06-14 13:20 UTC, TUM-Doepfert commented on lemlab/agents/prosumer.py
> +        df_potential_bids.rename(columns={f"power_{self.config_dict['R']}": "net_bids"}, inplace=True)
```suggestion
        df_potential_bids.rename(columns={f"power_{self.config_dict['id_meter_grid']}": "net_bids"}, inplace=True)
```
;)

2021-06-14 13:25 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +Specifically, the aim of these energy communities it to enable decentralized producers and consumers (prosumers) to
Accepted.

2021-06-14 13:26 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +might be entirely inflexible or they might prefer his electrical energy sources to produce as much carbon dioxide as
1. accepted.
2. intentionally tongue in cheek ;)

2021-06-14 13:27 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +Prosumers place bids on a **LEM platform**. This platform combines all market functionality, beginning with user
Rejected, grammatically correct the way it is.

2021-06-14 13:27 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +collection. **Aggregators** trade on a LEM on behalf of a group of prosumers. **Retailers** take care of coupling the
Rejected, see above.

2021-06-14 13:27 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +When does what happen in a LEM?
Rejected, see above.

2021-06-14 13:28 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +td, and are known as **pre-exchange-activities**, or they take place after delivery, which case they are known as
Accepted.

2021-06-14 13:29 UTC, sdlumpp commented on docs/01_Introduction_to_LEMs.rst
> +The above figure shows a slightly more detailed timeline. We see pre-clearing activities taking place during each of *n*
Perhaps. Will be discussed during the paper writing process.

2021-06-14 13:29 UTC, sdlumpp commented on lemlab/agents/prosumer.py
> +        df_potential_bids.rename(columns={f"power_{self.config_dict['R']}": "net_bids"}, inplace=True)
Resolved.

2021-06-15 13:33 UTC, TUM-Doepfert approved these changes
Test case run succesful

2021-06-15 13:33 UTC, merged